[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
torch_market = "E5b4rBqtS5jRvjHcYZ3ZSNo2sdSPJtauQKkEacKmmjqG"

[programs.localnet]
torch_market = "E5b4rBqtS5jRvjHcYZ3ZSNo2sdSPJtauQKkEacKmmjqG"

[programs.mainnet]
torch_market = "E5b4rBqtS5jRvjHcYZ3ZSNo2sdSPJtauQKkEacKmmjqG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""